set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_CXX_COMPILER g++ CACHE FILEPATH "G++ compiler")
set(CMAKE_C_COMPILER gcc CACHE FILEPATH "GCC compiler")
set(CMAKE_LINKER ld CACHE FILEPATH "GNU linker")
set(CMAKE_AR ar CACHE FILEPATH "GNU archiver")


